name: Destroy EKS with Terraform

on:
  workflow_dispatch:   # 👈 only runs when triggered manually

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # 3. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # 4. Terraform Init
      - name: Terraform Init
        working-directory: ./EKS
        run: terraform init

      # 5. Terraform Destroy
      - name: Terraform Destroy
        working-directory: ./EKS
        run: terraform destroy -auto-approve
